# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('type', models.IntegerField(choices=[(0, '首页轮播图'), (1, '活动轮播图')], default=0, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '轮播位',
                'verbose_name': '轮播位',
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='跳转路径')),
                ('detail', models.TextField(default='略', verbose_name='轮播详情')),
                ('image', models.ImageField(upload_to='Banner/%Y/%m', verbose_name='图片')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WechatDemo.Banner', verbose_name='轮播位')),
            ],
            options={
                'verbose_name_plural': '轮播内容',
                'verbose_name': '轮播内容',
            },
        ),
    ]
