# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-02 02:43
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WechatDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 10, 43, 39, 562568), verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='banneritem',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 10, 43, 39, 564333), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='banneritem',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='略', verbose_name='轮播详情'),
        ),
    ]
